backend:
  name: github
  repo:  tidiview/simple-backend  # Path to your GitHub repository
  branch: main
  base_url: https://simple-backend-oauth.herokuapp.com/
  auth_endpoint: /auth
site_url: https://tidiview.github.io/simple-backend/

logo_url: https://avatars0.githubusercontent.com/u/14911996?s=96&v=4
publish_mode: editorial_workflow
media_folder: "/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: cloudinary
  config:
    cloud_name: your_cloud_name
    api_key: your_api_key
show_preview_links: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - label: "Blog"
    name: "_posts"
    folder: "_posts"
    create: true
    # filter: {field: "language", value: "en"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Test Widget", name: "test_widget", widget: "async-select", url: "https://jsonplaceholder.typicode.com/users", valueField: "id", displayField: "name"}
    extension: "json"
    format: "json"
    json-frontmatter: true
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.json"
        extension: "json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
